"""empty message

Revision ID: de59e914e618
Revises: 5548327b6084
Create Date: 2024-01-05 18:38:02.753149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de59e914e618'
down_revision = '5548327b6084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('time_of_event', sa.DateTime(), nullable=True),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_description', sa.String(length=80), nullable=False),
    sa.Column('event_location', sa.String(length=80), nullable=False),
    sa.Column('event_address', sa.String(length=80), nullable=False),
    sa.Column('event_city', sa.String(length=80), nullable=False),
    sa.Column('event_state', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itinerary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_column('time_of_event')
        batch_op.drop_column('event_location')
        batch_op.drop_column('event_description')
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('event_description', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('event_location', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('time_of_event', sa.DATETIME(), nullable=True))

    op.drop_table('event')
    # ### end Alembic commands ###
